### ISSUE TITLE
What are liquid tags?

### ISSUE THREAD

**Issue by radoeka** [pelican-plugins/liquid-tags#13]
Is it possible to include an explanation about liquid tags and what is so special about them in the project description (README.md)?

It looks like a tag addition, but I can't extract their clear purpose from the description.

I hope this is a simple request, it will be useful and informational to the user unfamilair with liquid tags.

Thanks.

**Comment by mirekdlugosz** [comment]
Liquid tags are just strings that will be processed and replaced with some generated HTML during site generation. They take their name from [Liquid template language](https://shopify.github.io/liquid/), which is essentially the same thing as [Jinja](https://jinja.palletsprojects.com/) in Python.

Exact purpose really depends on tag. We have tags for generating images, embedding YouTube/Vimeo videos, embedding code from external file... In general, tags can be used anywhere where you want to generate some HTML in your markdown file. They work best when you want similar HTML in multiple markdown files, as they help to maintain consistency.

I wasn't around back then, but I believe initial set of tags was taken from [Jekyll liquid tags](https://jekyllrb.com/docs/liquid/tags/) and maintained compatible syntax. They are called "liquid tags" to make it easier for people migrating to Pelican from Jekyll.

Hope that helps. Feel free to use this comment as basis for improvement of README file, and send your suggestions in PR.

**Comment by radoeka** [comment]
Thanks for the explanation.  Liquid is referring to template, and the tags themselves are not liquide.
