### ISSUE TITLE
Error after fresh install

### ISSUE THREAD

**Issue by jaapnoordzij** [pelican-plugins/liquid-tags#19]
- Install a new Pelican with Markdown
- Create a skeleton site with pelican-quickstart
- Add a 1 or 2 line content file as test.md
- Install this plugin with pip and set the PLUGINS var
Generate the site with pelican .

Generates an error:
           ERROR    Could not process content/test.md                                                                                          log.py:96
                    LiquidTags.extendMarkdown() missing 1 required positional argument: 'md_globals'                                                    
Done: Processed 0 articles, 0 drafts, 0 hidden articles, 0 pages, 0 hidden pages and 0 draft pages in 0.09 seconds.

**Comment by mirekdlugosz** [comment]
I can reproduce the problem. Thanks for reporting!

Looks like liquid-tags expects `md_globals` argument, which was [deprecated in Markdown package back in 2018](https://github.com/Python-Markdown/markdown/pull/697). Markdown finally removed backwards-compatibility in release 3.4, released about two weeks ago.

We never use that variable, so fix is easy, but there's another issue under it. I will need more time to debug that.

In the meantime, you can downgrade markdown to last known working version:
```
pip install markdown==3.3.7
```

By the way, you don't need to include liquid_tags in `PLUGINS` var (unless you still use old-style pelican plugin). However, you should set `LIQUID_TAGS` variable for plugin to do anything interesting.

**Comment by jaapnoordzij** [comment]
Thank you for the workaround!

**Comment by mirekdlugosz** [comment]
@jaapnoordzij I have now merged the fix and released new version of a plugin. I can no longer reproduce the problem on fresh install.

You should now be able to update markdown package. Let us know if you encounter more issues.
